// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtjAmR17Wib257Rs7JwbkUuF7XI0daWo',
    appId: '1:86125236762:web:f55f685c315e2ac29277a3',
    messagingSenderId: '86125236762',
    projectId: 'cookly-7c81b',
    authDomain: 'cookly-7c81b.firebaseapp.com',
    storageBucket: 'cookly-7c81b.firebasestorage.app',
    measurementId: 'G-SE2ET9WRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6kubuEAr11i4UpqCz3tNo3M33TcXc40',
    appId: '1:86125236762:android:770dbc23caf814a39277a3',
    messagingSenderId: '86125236762',
    projectId: 'cookly-7c81b',
    storageBucket: 'cookly-7c81b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbQPmeBiusjycY_uKBesGxtENRT0ylPI',
    appId: '1:86125236762:ios:08dcb3ed17ee18779277a3',
    messagingSenderId: '86125236762',
    projectId: 'cookly-7c81b',
    storageBucket: 'cookly-7c81b.firebasestorage.app',
    iosBundleId: 'com.example.recetasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbQPmeBiusjycY_uKBesGxtENRT0ylPI',
    appId: '1:86125236762:ios:08dcb3ed17ee18779277a3',
    messagingSenderId: '86125236762',
    projectId: 'cookly-7c81b',
    storageBucket: 'cookly-7c81b.firebasestorage.app',
    iosBundleId: 'com.example.recetasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJtjAmR17Wib257Rs7JwbkUuF7XI0daWo',
    appId: '1:86125236762:web:ebc935b3b47bc7dc9277a3',
    messagingSenderId: '86125236762',
    projectId: 'cookly-7c81b',
    authDomain: 'cookly-7c81b.firebaseapp.com',
    storageBucket: 'cookly-7c81b.firebasestorage.app',
    measurementId: 'G-P02NQLNLT4',
  );
}
